"""fix payment <-> order relationship

Revision ID: 7c3396c2c1ef
Revises: 6ec8b5b63886
Create Date: 2026-09-15 03:25:26.369683

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c3396c2c1ef"
down_revision: Union[str, Sequence[str], None] = "6ec8b5b63886"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
