"""Initial migration

Revision ID: beff147ec96a
Revises:
Create Date: 2026-09-13 21:15:37.054801

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "beff147ec96a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
